# French translations for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-07-16 16:22+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language: fr\n"
"Language-Team: fr <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: frictionless/actions/convert.py:42
msgid "Resource with data type \"{resource_datatype}\" is not convertible"
msgstr ""

#: frictionless/actions/extract.py:50
msgid "Resource with data type \"{resource_datatype}\" is not extractable"
msgstr ""

#: frictionless/actions/index.py:40
msgid "Resource with data type \"{resource_datatype}\" is not indexable"
msgstr ""

#: frictionless/actions/transform.py:52
msgid "Resource with data type \"{resource_datatype}\" is not transformable"
msgstr ""

#: frictionless/catalog/catalog.py:102
msgid "dataset \"{name}\" does not exist"
msgstr ""

#: frictionless/checklist/check.py:118
msgid "Check \"code\" is deprecated in favor of \"type\""
msgstr ""

#: frictionless/checklist/check.py:119 frictionless/inquiry/task.py:215
#: frictionless/pipeline/pipeline.py:123 frictionless/pipeline/step.py:98
#: frictionless/resource/resource.py:741 frictionless/resource/resource.py:772
#: frictionless/resource/resource.py:787
msgid "(it will be removed in the next major version)"
msgstr ""

#: frictionless/checks/baseline.py:66
msgid "the source is empty"
msgstr ""

#: frictionless/checks/baseline.py:83 frictionless/checks/baseline.py:90
#: frictionless/checks/baseline.py:97 frictionless/checks/baseline.py:104
#, python-format
msgid "expected is \"%s\" and actual is \"%s\""
msgstr ""

#: frictionless/checks/cell/ascii_value.py:36
msgid "the cell contains non-ascii characters"
msgstr ""

#: frictionless/checks/cell/deviated_cell.py:77
#, python-format
msgid "cell at row \"%s\" and field \"%s\" has deviated size"
msgstr ""

#: frictionless/checks/cell/deviated_value.py:67
#, python-format
msgid "deviated value check requires field \"%s\" to exist"
msgstr ""

#: frictionless/checks/cell/deviated_value.py:70
#, python-format
msgid "deviated value check requires field \"%s\" to be numeric"
msgstr ""

#: frictionless/checks/cell/deviated_value.py:73
#, python-format
msgid "deviated value check supports only average functions \"%s\""
msgstr ""

#: frictionless/checks/cell/deviated_value.py:95
#, python-format
msgid "calculation issue \"%s\""
msgstr ""

#: frictionless/checks/cell/deviated_value.py:102
#, python-format
msgid ""
"value \"%s\" in row at position \"%s\" and field \"%s\" is deviated "
"\"[%.2f, %.2f]\""
msgstr ""

#: frictionless/checks/cell/forbidden_value.py:40
#, python-format
msgid "forbidden value check requires field \"%s\""
msgstr ""

#: frictionless/checks/cell/forbidden_value.py:48
#, python-format
msgid "forbidden values are \"%s\""
msgstr ""

#: frictionless/checks/cell/required_value.py:47
#, python-format
msgid "required value check requires field \"%s\" to exist"
msgstr ""

#: frictionless/checks/cell/required_value.py:60
#, python-format
msgid ""
"The value \"%s\" is required to be present in field \"%s\" in at least "
"one row."
msgstr ""

#: frictionless/checks/cell/sequential_value.py:42
#, python-format
msgid "sequential value check requires field \"%s\""
msgstr ""

#: frictionless/checks/cell/sequential_value.py:56
msgid "the value is not sequential"
msgstr ""

#: frictionless/checks/cell/truncated_value.py:64
msgid "value  is probably truncated"
msgstr ""

#: frictionless/checks/row/duplicate_row.py:42
#, python-format
msgid "the same as row at position \"%s\""
msgstr ""

#: frictionless/checks/row/row_constraint.py:42
#, python-format
msgid "the row constraint to conform is \"%s\""
msgstr ""

#: frictionless/checks/table/table_dimensions.py:70
#, python-format
msgid "number of fields is %s, the required is %s"
msgstr ""

#: frictionless/checks/table/table_dimensions.py:77
#, python-format
msgid "number of fields is %s, the minimum is %s"
msgstr ""

#: frictionless/checks/table/table_dimensions.py:84
#, python-format
msgid "number of fields is %s, the maximum is %s"
msgstr ""

#: frictionless/checks/table/table_dimensions.py:94
#, python-format
msgid "number of rows is %s, the required is %s"
msgstr ""

#: frictionless/checks/table/table_dimensions.py:101
#, python-format
msgid "number of rows is %s, the minimum is %s"
msgstr ""

#: frictionless/checks/table/table_dimensions.py:108
#, python-format
msgid "number of rows is %s, the maximum is %s"
msgstr ""

#: frictionless/detector/detector.py:411
msgid "\"schema_sync\" requires unique labels in the header"
msgstr ""

#: frictionless/dialect/dialect.py:122
msgid "control \"{control_type}\" already exists"
msgstr ""

#: frictionless/dialect/dialect.py:139
msgid "control \"{type}\" does not exist"
msgstr ""

#: frictionless/errors/cell.py:23 frictionless/errors/cell.py:24
#: frictionless/errors/cell.py:25 frictionless/errors/header.py:20
#: frictionless/errors/header.py:21
msgid "Cell Error"
msgstr ""

#: frictionless/errors/cell.py:71
msgid "Field {field_name} is not in the row"
msgstr ""

#: frictionless/errors/cell.py:86
msgid "Extra Cell"
msgstr ""

#: frictionless/errors/cell.py:87
msgid ""
"This row has more values compared to the header row (the first row in the"
" data source). A key concept is that all the rows in tabular data must "
"have the same number of columns."
msgstr ""

#: frictionless/errors/cell.py:88
msgid ""
"Row at position \"{rowNumber}\" has an extra value in field at position "
"\"{fieldNumber}\""
msgstr ""

#: frictionless/errors/cell.py:93
msgid "Missing Cell"
msgstr ""

#: frictionless/errors/cell.py:94
msgid ""
"This row has less values compared to the header row (the first row in the"
" data source). A key concept is that all the rows in tabular data must "
"have the same number of columns."
msgstr ""

#: frictionless/errors/cell.py:95
msgid ""
"Row at position \"{rowNumber}\" has a missing cell in field "
"\"{fieldName}\" at position \"{fieldNumber}\""
msgstr ""

#: frictionless/errors/cell.py:100
msgid "Type Error"
msgstr ""

#: frictionless/errors/cell.py:101
msgid "The value does not match the schema type and format for this field."
msgstr ""

#: frictionless/errors/cell.py:102
msgid ""
"Type error in the cell \"{cell}\" in row \"{rowNumber}\" and field "
"\"{fieldName}\" at position \"{fieldNumber}\": {note}"
msgstr ""

#: frictionless/errors/cell.py:107
msgid "Constraint Error"
msgstr ""

#: frictionless/errors/cell.py:108
msgid "A field value does not conform to a constraint."
msgstr ""

#: frictionless/errors/cell.py:109
msgid ""
"The cell \"{cell}\" in row at position \"{rowNumber}\" and field "
"\"{fieldName}\" at position \"{fieldNumber}\" does not conform to a "
"constraint: {note}"
msgstr ""

#: frictionless/errors/cell.py:114
msgid "Unique Error"
msgstr ""

#: frictionless/errors/cell.py:115
msgid ""
"This field is a unique field but it contains a value that has been used "
"in another row."
msgstr ""

#: frictionless/errors/cell.py:116
msgid ""
"Row at position \"{rowNumber}\" has unique constraint violation in field "
"\"{fieldName}\" at position \"{fieldNumber}\": {note}"
msgstr ""

#: frictionless/errors/cell.py:121
msgid "Truncated Value"
msgstr ""

#: frictionless/errors/cell.py:122
msgid "The value is possible truncated."
msgstr ""

#: frictionless/errors/cell.py:123 frictionless/errors/cell.py:130
#: frictionless/errors/cell.py:137 frictionless/errors/cell.py:144
msgid ""
"The cell {cell} in row at position {rowNumber} and field {fieldName} at "
"position {fieldNumber} has an error: {note}"
msgstr ""

#: frictionless/errors/cell.py:128
msgid "Forbidden Value"
msgstr ""

#: frictionless/errors/cell.py:129
msgid "The value is forbidden."
msgstr ""

#: frictionless/errors/cell.py:135
msgid "Sequential Value"
msgstr ""

#: frictionless/errors/cell.py:136
msgid "The value is not sequential."
msgstr ""

#: frictionless/errors/cell.py:142
msgid "Ascii Value"
msgstr ""

#: frictionless/errors/cell.py:143
msgid "The cell contains non-ascii characters."
msgstr ""

#: frictionless/errors/data.py:9
msgid "Data Error"
msgstr ""

#: frictionless/errors/data.py:10
msgid "There is a data error."
msgstr ""

#: frictionless/errors/data.py:11
msgid "Data error: {note}"
msgstr ""

#: frictionless/errors/file.py:9
msgid "File Error"
msgstr ""

#: frictionless/errors/file.py:10
msgid "There is a file error."
msgstr ""

#: frictionless/errors/file.py:11
msgid "General file error: {note}"
msgstr ""

#: frictionless/errors/file.py:17
msgid "Hash Count Error"
msgstr ""

#: frictionless/errors/file.py:18 frictionless/errors/file.py:25
#: frictionless/errors/table.py:18 frictionless/errors/table.py:25
#: frictionless/errors/table.py:32
msgid "This error can happen if the data is corrupted."
msgstr ""

#: frictionless/errors/file.py:19
msgid "The data source does not match the expected hash count: {note}"
msgstr ""

#: frictionless/errors/file.py:24
msgid "Byte Count Error"
msgstr ""

#: frictionless/errors/file.py:26
msgid "The data source does not match the expected byte count: {note}"
msgstr ""

#: frictionless/errors/header.py:19
msgid "Header Error"
msgstr ""

#: frictionless/errors/header.py:46
msgid "Blank Header"
msgstr ""

#: frictionless/errors/header.py:47
msgid "This header is empty. A header should contain at least one value."
msgstr ""

#: frictionless/errors/header.py:48
msgid "Header is completely blank"
msgstr ""

#: frictionless/errors/label.py:18 frictionless/errors/label.py:19
#: frictionless/errors/label.py:20
msgid "Label Error"
msgstr ""

#: frictionless/errors/label.py:51
msgid "Extra Label"
msgstr ""

#: frictionless/errors/label.py:52
msgid ""
"The header of the data source contains label that does not exist in the "
"provided schema."
msgstr ""

#: frictionless/errors/label.py:53
msgid ""
"There is an extra label \"{label}\" in header at position "
"\"{fieldNumber}\""
msgstr ""

#: frictionless/errors/label.py:58
msgid "Missing Label"
msgstr ""

#: frictionless/errors/label.py:59
msgid ""
"Based on the schema there should be a label that is missing in the data's"
" header."
msgstr ""

#: frictionless/errors/label.py:60
msgid ""
"There is a missing label in the header's field \"{fieldName}\" at "
"position \"{fieldNumber}\""
msgstr ""

#: frictionless/errors/label.py:65
msgid "Blank Label"
msgstr ""

#: frictionless/errors/label.py:66
msgid ""
"A label in the header row is missing a value. Label should be provided "
"and not be blank."
msgstr ""

#: frictionless/errors/label.py:67
msgid "Label in the header in field at position \"{fieldNumber}\" is blank"
msgstr ""

#: frictionless/errors/label.py:72
msgid "Duplicate Label"
msgstr ""

#: frictionless/errors/label.py:73
msgid ""
"Two columns in the header row have the same value. Column names should be"
" unique."
msgstr ""

#: frictionless/errors/label.py:74
msgid ""
"Label \"{label}\" in the header at position \"{fieldNumber}\" is "
"duplicated to a label: {note}"
msgstr ""

#: frictionless/errors/label.py:79
msgid "Incorrect Label"
msgstr ""

#: frictionless/errors/label.py:80
msgid ""
"One of the data source header does not match the field name defined in "
"the schema."
msgstr ""

#: frictionless/errors/label.py:81
msgid ""
"Label \"{label}\" in field {fieldName} at position \"{fieldNumber}\" does"
" not match the field name in the schema"
msgstr ""

#: frictionless/errors/metadata.py:9
msgid "Metadata Error"
msgstr ""

#: frictionless/errors/metadata.py:10
msgid "There is a metadata error."
msgstr ""

#: frictionless/errors/metadata.py:11
msgid "Metadata error: {note}"
msgstr ""

#: frictionless/errors/metadata.py:16
msgid "Catalog Error"
msgstr ""

#: frictionless/errors/metadata.py:17 frictionless/errors/metadata.py:24
#: frictionless/errors/metadata.py:80 frictionless/errors/resource.py:10
msgid "A validation cannot be processed."
msgstr ""

#: frictionless/errors/metadata.py:18
msgid "The data catalog has an error: {note}"
msgstr ""

#: frictionless/errors/metadata.py:23
msgid "Dataset Error"
msgstr ""

#: frictionless/errors/metadata.py:25
msgid "The dataset has an error: {note}"
msgstr ""

#: frictionless/errors/metadata.py:30
msgid "Checklist Error"
msgstr ""

#: frictionless/errors/metadata.py:31
msgid "Provided checklist is not valid."
msgstr ""

#: frictionless/errors/metadata.py:32
msgid "Checklist is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:37
msgid "Check Error"
msgstr ""

#: frictionless/errors/metadata.py:38
msgid "Provided check is not valid"
msgstr ""

#: frictionless/errors/metadata.py:39
msgid "Check is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:44
msgid "Detector Error"
msgstr ""

#: frictionless/errors/metadata.py:45
msgid "Provided detector is not valid."
msgstr ""

#: frictionless/errors/metadata.py:46
msgid "Detector is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:51
msgid "Dialect Error"
msgstr ""

#: frictionless/errors/metadata.py:52
msgid "Provided dialect is not valid."
msgstr ""

#: frictionless/errors/metadata.py:53
msgid "Dialect is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:58
msgid "Control Error"
msgstr ""

#: frictionless/errors/metadata.py:59
msgid "Provided control is not valid."
msgstr ""

#: frictionless/errors/metadata.py:60
msgid "Control is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:65
msgid "Inquiry Error"
msgstr ""

#: frictionless/errors/metadata.py:66
msgid "Provided inquiry is not valid."
msgstr ""

#: frictionless/errors/metadata.py:67
msgid "Inquiry is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:72
msgid "Inquiry Task Error"
msgstr ""

#: frictionless/errors/metadata.py:73
msgid "Provided inquiry task is not valid."
msgstr ""

#: frictionless/errors/metadata.py:74
msgid "Inquiry task is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:79
msgid "Package Error"
msgstr ""

#: frictionless/errors/metadata.py:81
msgid "The data package has an error: {note}"
msgstr ""

#: frictionless/errors/metadata.py:86
msgid "Pipeline Error"
msgstr ""

#: frictionless/errors/metadata.py:87
msgid "Provided pipeline is not valid."
msgstr ""

#: frictionless/errors/metadata.py:88
msgid "Pipeline is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:93
msgid "Step Error"
msgstr ""

#: frictionless/errors/metadata.py:94
msgid "Provided step is not valid"
msgstr ""

#: frictionless/errors/metadata.py:95
msgid "Step is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:100
msgid "Report Error"
msgstr ""

#: frictionless/errors/metadata.py:101
msgid "Provided report is not valid."
msgstr ""

#: frictionless/errors/metadata.py:102
msgid "Report is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:107
msgid "Report Task Error"
msgstr ""

#: frictionless/errors/metadata.py:108
msgid "Provided report task is not valid."
msgstr ""

#: frictionless/errors/metadata.py:109
msgid "Report task is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:114
msgid "Schema Error"
msgstr ""

#: frictionless/errors/metadata.py:115
msgid "Provided schema is not valid."
msgstr ""

#: frictionless/errors/metadata.py:116
msgid "Schema is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:121
msgid "Field Error"
msgstr ""

#: frictionless/errors/metadata.py:122
msgid "Provided field is not valid."
msgstr ""

#: frictionless/errors/metadata.py:123
msgid "Field is not valid: {note}"
msgstr ""

#: frictionless/errors/metadata.py:128
msgid "Stats Error"
msgstr ""

#: frictionless/errors/metadata.py:129
msgid "Stats object has an error."
msgstr ""

#: frictionless/errors/metadata.py:130
msgid "Stats object has an error: {note}"
msgstr ""

#: frictionless/errors/resource.py:9
msgid "Resource Error"
msgstr ""

#: frictionless/errors/resource.py:11
msgid "The data resource has an error: {note}"
msgstr ""

#: frictionless/errors/resource.py:16
msgid "Source Error"
msgstr ""

#: frictionless/errors/resource.py:17
msgid "Data reading error because of not supported or inconsistent contents."
msgstr ""

#: frictionless/errors/resource.py:18
msgid "The data source has not supported or has inconsistent contents: {note}"
msgstr ""

#: frictionless/errors/resource.py:23
msgid "Scheme Error"
msgstr ""

#: frictionless/errors/resource.py:24
msgid "Data reading error because of incorrect scheme."
msgstr ""

#: frictionless/errors/resource.py:25
msgid "The data source could not be successfully loaded: {note}"
msgstr ""

#: frictionless/errors/resource.py:30
msgid "Format Error"
msgstr ""

#: frictionless/errors/resource.py:31
msgid "Data reading error because of incorrect format."
msgstr ""

#: frictionless/errors/resource.py:32
msgid "The data source could not be successfully parsed: {note}"
msgstr ""

#: frictionless/errors/resource.py:37
msgid "Encoding Error"
msgstr ""

#: frictionless/errors/resource.py:38
msgid "Data reading error because of an encoding problem."
msgstr ""

#: frictionless/errors/resource.py:39
msgid "The data source could not be successfully decoded: {note}"
msgstr ""

#: frictionless/errors/resource.py:44
msgid "Compression Error"
msgstr ""

#: frictionless/errors/resource.py:45
msgid "Data reading error because of a decompression problem."
msgstr ""

#: frictionless/errors/resource.py:46
msgid "The data source could not be successfully decompressed: {note}"
msgstr ""

#: frictionless/errors/row.py:25 frictionless/errors/row.py:26
#: frictionless/errors/row.py:27
msgid "Row Error"
msgstr ""

#: frictionless/errors/row.py:64
msgid "Blank Row"
msgstr ""

#: frictionless/errors/row.py:65
msgid "This row is empty. A row should contain at least one value."
msgstr ""

#: frictionless/errors/row.py:66
msgid "Row at position \"{rowNumber}\" is completely blank"
msgstr ""

#: frictionless/errors/row.py:71
msgid "PrimaryKey Error"
msgstr ""

#: frictionless/errors/row.py:72
msgid "Values in the primary key fields should be unique for every row"
msgstr ""

#: frictionless/errors/row.py:73
msgid "Row at position \"{rowNumber}\" violates the primary key: {note}"
msgstr ""

#: frictionless/errors/row.py:79
msgid "ForeignKey Error"
msgstr ""

#: frictionless/errors/row.py:80
msgid "Values in the foreign key fields should exist in the reference table"
msgstr ""

#: frictionless/errors/row.py:81
msgid "Row at position \"{rowNumber}\" violates the foreign key: {note}"
msgstr ""

#: frictionless/errors/row.py:140
msgid "Duplicate Row"
msgstr ""

#: frictionless/errors/row.py:141
msgid "The row is duplicated."
msgstr ""

#: frictionless/errors/row.py:142
msgid "Row at position {rowNumber} is duplicated: {note}"
msgstr ""

#: frictionless/errors/row.py:147
msgid "Row Constraint"
msgstr ""

#: frictionless/errors/row.py:148
msgid "The value does not conform to the row constraint."
msgstr ""

#: frictionless/errors/row.py:149
msgid "The row at position {rowNumber} has an error: {note}"
msgstr ""

#: frictionless/errors/table.py:9
msgid "Table Error"
msgstr ""

#: frictionless/errors/table.py:10
msgid "There is a table error."
msgstr ""

#: frictionless/errors/table.py:11
msgid "General table error: {note}"
msgstr ""

#: frictionless/errors/table.py:17
msgid "Field Count Error"
msgstr ""

#: frictionless/errors/table.py:19
msgid "The data source does not match the expected field count: {note}"
msgstr ""

#: frictionless/errors/table.py:24
msgid "Row Count Error"
msgstr ""

#: frictionless/errors/table.py:26
msgid "The data source does not match the expected row count: {note}"
msgstr ""

#: frictionless/errors/table.py:31
msgid "Table dimensions error"
msgstr ""

#: frictionless/errors/table.py:33
msgid "The data source does not have the required dimensions: {note}"
msgstr ""

#: frictionless/errors/table.py:38
msgid "Deviated Value"
msgstr ""

#: frictionless/errors/table.py:39
msgid "The value is deviated."
msgstr ""

#: frictionless/errors/table.py:40
msgid "There is a possible error because the value is deviated: {note}"
msgstr ""

#: frictionless/errors/table.py:45
msgid "Deviated cell"
msgstr ""

#: frictionless/errors/table.py:46
msgid "The cell is deviated."
msgstr ""

#: frictionless/errors/table.py:47
msgid "There is a possible error because the cell is deviated: {note}"
msgstr ""

#: frictionless/errors/table.py:52
msgid "Required Value"
msgstr ""

#: frictionless/errors/table.py:53
msgid "The required values are missing."
msgstr ""

#: frictionless/errors/table.py:54
msgid "Required values not found: {note}"
msgstr ""

#: frictionless/formats/excel/parsers/xls.py:66
#: frictionless/formats/excel/parsers/xlsx.py:101
#, python-format
msgid "Excel document \"%s\" does not have a sheet \"%s\""
msgstr ""

#: frictionless/formats/excel/parsers/xlsx.py:91
msgid "invalid excel file \"{resource_path}\""
msgstr ""

#: frictionless/formats/gsheets/parser.py:50
msgid "Cannot save {path}"
msgstr ""

#: frictionless/formats/inline/parser.py:73
#: frictionless/formats/inline/parser.py:82
#: frictionless/formats/inline/parser.py:88
msgid "unsupported inline data"
msgstr ""

#: frictionless/formats/json/parsers/json.py:47
msgid "cannot extract JSON tabular data from \"{resource_normpath}\""
msgstr ""

#: frictionless/formats/ods/parser.py:50
#, python-format
msgid "OpenOffice document \"%s\" does not have a sheet \"%s\""
msgstr ""

#: frictionless/formats/yaml/parser.py:45
msgid "cannot extract YAML tabular data from \"{resource_normpath}\""
msgstr ""

#: frictionless/formats/zip/adapter.py:84
#: frictionless/formats/zip/adapter.py:96
msgid "Zipping usafe \"{normpath}\" is not supported"
msgstr ""

#: frictionless/indexer/indexer.py:106
msgid "Fast mode is only supported for Postgres/Sqlite"
msgstr ""

#: frictionless/inquiry/task.py:214
msgid "InquiryTask \"source\" is deprecated in favor of \"resource/package\""
msgstr ""

#: frictionless/inquiry/task.py:233 frictionless/package/package.py:630
msgid "path \"{item}\" is not safe"
msgstr ""

#: frictionless/inquiry/task.py:241
msgid "one of the properties \"path\", \"resource\", or \"package\" is required"
msgstr ""

#: frictionless/metadata/metadata.py:188 frictionless/metadata/metadata.py:202
msgid "descriptor is not valid"
msgstr ""

#: frictionless/metadata/metadata.py:339
msgid "cannot retrieve metadata \"{descriptor}\" because \"{exception}\""
msgstr ""

#: frictionless/package/package.py:230
msgid "resource \"{name}\" does not exist"
msgstr ""

#: frictionless/package/package.py:238
msgid "resource \"{name}\" is not tabular"
msgstr ""

#: frictionless/package/package.py:311
msgid "Not supported target: {target} or control"
msgstr ""

#: frictionless/package/package.py:314
msgid "Not supported action"
msgstr ""

#: frictionless/package/package.py:639
msgid "names of the resources are not unique"
msgstr ""

#: frictionless/package/package.py:648
msgid "property \"created\" is not valid \"datetime\""
msgstr ""

#: frictionless/package/package.py:654 frictionless/resource/resource.py:823
msgid "license requires \"path\" or \"name\": {item}"
msgstr ""

#: frictionless/package/package.py:664 frictionless/resource/resource.py:833
msgid "property \"{name}[].email\" is not valid \"email\""
msgstr ""

#: frictionless/package/package.py:685
msgid ""
"profile \"tabular-data-package\" requires all the resources to be "
"\"tabular-data-resource\""
msgstr ""

#: frictionless/package/package.py:691
msgid "\"{name}\" should be set as \"resource.schema.{name}\""
msgstr ""

#: frictionless/pipeline/pipeline.py:71
msgid "step \"{type}\" does not exist"
msgstr ""

#: frictionless/pipeline/pipeline.py:122
msgid "Pipeline \"tasks[].steps\" is deprecated in favor of \"steps\""
msgstr ""

#: frictionless/pipeline/step.py:97
msgid "Step \"code\" is deprecated in favor of \"type\""
msgstr ""

#: frictionless/portals/ckan/adapter.py:86
msgid "Your package has no name. CKAN requires a name to publish a package"
msgstr ""

#: frictionless/portals/ckan/adapter.py:193
msgid "CKAN API error:"
msgstr ""

#: frictionless/portals/ckan/adapter.py:252
msgid "Error in CKAN dataset {descriptor_id}: {e}"
msgstr ""

#: frictionless/portals/ckan/adapter.py:310
msgid "CKAN returned an error: "
msgstr ""

#: frictionless/portals/github/adapter.py:31
msgid "Repo and user is required"
msgstr ""

#: frictionless/portals/github/adapter.py:52
#: frictionless/portals/github/adapter.py:175
#: frictionless/portals/github/adapter.py:228
#: frictionless/portals/zenodo/adapter.py:49
#: frictionless/portals/zenodo/adapter.py:215
msgid "Package/s not found"
msgstr ""

#: frictionless/portals/github/adapter.py:72
#: frictionless/portals/github/adapter.py:97
#: frictionless/portals/github/adapter.py:117
msgid "Github API error:"
msgstr ""

#: frictionless/portals/github/adapter.py:147
msgid "Repo or user or search text is required"
msgstr ""

#: frictionless/portals/github/adapter.py:159
msgid "Github API error"
msgstr ""

#: frictionless/portals/zenodo/adapter.py:35
msgid "Record is required."
msgstr ""

#: frictionless/portals/zenodo/adapter.py:60
msgid "Api key is required for zenodo publishing"
msgstr ""

#: frictionless/portals/zenodo/adapter.py:146
#: frictionless/portals/zenodo/adapter.py:206
msgid "Zenodo API error"
msgstr ""

#: frictionless/report/report.py:80
msgid "The \"report.error\" is available for single error reports"
msgstr ""

#: frictionless/report/report.py:88
msgid "The \"report.task\" is available for single task reports"
msgstr ""

#: frictionless/report/task.py:79
msgid "The \"task.error\" is available for single error tasks"
msgstr ""

#: frictionless/report/task.py:122
msgid "File Place"
msgstr ""

#: frictionless/report/task.py:123
msgid "File Size"
msgstr ""

#: frictionless/report/task.py:123
msgid "(file not found)"
msgstr ""

#: frictionless/report/task.py:124
msgid "Total Time"
msgstr ""

#: frictionless/report/task.py:124
msgid "{seconds} Seconds"
msgstr ""

#: frictionless/report/task.py:125
msgid "Rows Checked"
msgstr ""

#: frictionless/report/task.py:128
msgid "Total Errors"
msgstr ""

#: frictionless/report/task.py:134
msgid "Name"
msgstr ""

#: frictionless/report/task.py:134
msgid "Value"
msgstr ""

#: frictionless/resource/resource.py:366 frictionless/resource/resource.py:377
#: frictionless/resources/table.py:58
msgid "resource is not open or non binary"
msgstr ""

#: frictionless/resource/resource.py:391
msgid "resource is not open or non textual"
msgstr ""

#: frictionless/resource/resource.py:502
msgid "Resource.infer cannot be used on a open resource"
msgstr ""

#: frictionless/resource/resource.py:740
msgid "Resource \"stats.hash\" is deprecated in favor of \"stats.sha256/md5\""
msgstr ""

#: frictionless/resource/resource.py:771
msgid "Resource \"compression=no\" is deprecated in favor not set value"
msgstr ""

#: frictionless/resource/resource.py:786
msgid "Resource \"layout\" is deprecated in favor of \"dialect\""
msgstr ""

#: frictionless/resource/resource.py:812
msgid "one of the properties \"path\" or \"data\" is required"
msgstr ""

#: frictionless/resource/resource.py:817
msgid "properties \"path\" and \"data\" is mutually exclusive"
msgstr ""

#: frictionless/resource/resource.py:849
msgid "profile \"tabular-data-resource\" requires \"schema\" to be present"
msgstr ""

#: frictionless/resource/resource.py:855
msgid "\"{name}\" should be set as \"schema.{name}\""
msgstr ""

#: frictionless/resources/file.py:53 frictionless/resources/text.py:41
msgid "target must be a text resource"
msgstr ""

#: frictionless/resources/json.py:65
msgid "target must be a json resource"
msgstr ""

#: frictionless/resources/table.py:72 frictionless/resources/table.py:82
#: frictionless/resources/table.py:96 frictionless/resources/table.py:106
#: frictionless/resources/table.py:116 frictionless/resources/table.py:127
#: frictionless/resources/table.py:138
msgid "resource is not open"
msgstr ""

#: frictionless/resources/table.py:241
msgid "package is required for FK: \"{fk}\""
msgstr ""

#: frictionless/resources/table.py:244
msgid ""
"failed to handle a foreign key for resource \"{name}\" as resource "
"\"{source_name}\" does not exist"
msgstr ""

#: frictionless/resources/table.py:331 frictionless/resources/table.py:347
#, python-format
msgid "the same as in the row at position %s"
msgstr ""

#: frictionless/resources/table.py:339
msgid "cells composing the primary keys are all \"None\""
msgstr ""

#: frictionless/resources/table.py:362
#, python-format
msgid "for \"%s\": values \"%s\" not found in the lookup table \"%s\" as \"%s\""
msgstr ""

#: frictionless/resources/table.py:460
msgid "target must be a table resource"
msgstr ""

#: frictionless/resources/table.py:515
msgid "Cannot convert to the existent path \"{to_path}\""
msgstr ""

#: frictionless/schema/field.py:93
msgid "Use \"schema.set_field_type()\" to update the type of the field"
msgstr ""

#: frictionless/schema/field.py:143 frictionless/schema/field.py:187
msgid "type is \"{type}/{format}\""
msgstr ""

#: frictionless/schema/field.py:149
msgid "constraint \"{name}\" is \"{constraint}\""
msgstr ""

#: frictionless/schema/field.py:257
msgid "constraint \"{name}\" is not supported by type \"{type}\""
msgstr ""

#: frictionless/schema/field.py:271
msgid "example value \"{example}\" for field \"{field_name}\" is not valid"
msgstr ""

#: frictionless/schema/field.py:277
msgid "\"{name}\" should be set as \"constraints.{name}\""
msgstr ""

#: frictionless/schema/schema.py:124
msgid "field \"{name}\" does not exist"
msgstr ""

#: frictionless/schema/schema.py:368
msgid "names of the fields are not unique"
msgstr ""

#: frictionless/schema/schema.py:375
#, python-format
msgid "primary key \"%s\" does not match the fields \"%s\""
msgstr ""

#: frictionless/schema/schema.py:384
#, python-format
msgid "foreign key \"%s\" does not match the fields \"%s\""
msgstr ""

#: frictionless/schema/schema.py:388
#, python-format
msgid "foreign key fields \"%s\" does not match the reference fields \"%s\""
msgstr ""

#: frictionless/schemes/local/adapter.py:37
msgid "Cannot read package"
msgstr ""

#: frictionless/schemes/stream/loader.py:20
msgid "only local streams are supported: {byte_stream}"
msgstr ""

#: frictionless/schemes/stream/loader.py:26
msgid "cannot open a stream in the byte mode: {byte_stream}"
msgstr ""

#: frictionless/schemes/stream/loader.py:52
msgid "cannot re-open a byte stream: {byte_stream}"
msgstr ""

#: frictionless/steps/resource/resource_remove.py:38
#: frictionless/steps/resource/resource_transform.py:45
msgid "No resource \"{name}\""
msgstr ""

#: frictionless/steps/resource/resource_update.py:45
msgid "Property \"name\" is required for \"resource_update\" within a package"
msgstr ""

#: frictionless/system/loader.py:72 frictionless/system/loader.py:85
#: frictionless/system/loader.py:98
msgid "loader is not open"
msgstr ""

#: frictionless/system/loader.py:214
msgid "the archive is empty"
msgstr ""

#: frictionless/system/loader.py:259
msgid "compression \"{compression}\" is not supported"
msgstr ""

#: frictionless/system/parser.py:68
msgid "parser is not open or non requiring loader"
msgstr ""

#: frictionless/system/parser.py:78 frictionless/system/parser.py:88
msgid "parser is not open"
msgstr ""

#: frictionless/system/system.py:230
msgid "scheme \"{name}\" is not supported"
msgstr ""

#: frictionless/system/system.py:248
msgid "format \"{name}\" is not supported"
msgstr ""

#: frictionless/system/system.py:285
msgid "check type \"{type}\" is not supported"
msgstr ""

#: frictionless/system/system.py:295
msgid "control type \"{type}\" is not supported"
msgstr ""

#: frictionless/system/system.py:309
msgid "error type \"{type}\" is not supported"
msgstr ""

#: frictionless/system/system.py:323
msgid "field type \"{type}\" is not supported"
msgstr ""

#: frictionless/system/system.py:333
msgid "package type \"{type}\" is not supported"
msgstr ""

#: frictionless/system/system.py:353
msgid "resource type \"{type}\" is not supported"
msgstr ""

#: frictionless/system/system.py:367
msgid "step type \"{type}\" is not supported"
msgstr ""

#: frictionless/table/header.py:194
#, python-format
msgid "at position \"%s\""
msgstr ""

#: frictionless/table/row.py:68 frictionless/table/row.py:283
msgid "Row does not have a field {key}"
msgstr ""

#: frictionless/transformer/transformer.py:27
#: frictionless/transformer/transformer.py:49
msgid "\"{get_name(step)}\" raises \"{exception}\""
msgstr ""

#: frictionless/transformer/transformer.py:93
msgid "\"{get_name(self.step)}\" raises \"{exception}\""
msgstr ""

#: frictionless/validator/validator.py:116
msgid "hash is ignored; supported algorithms: md5/sha256"
msgstr ""

#: frictionless/validator/validator.py:173
msgid "reached row limit: {limit_rows}"
msgstr ""

#: frictionless/validator/validator.py:182
msgid "reached error limit: {limit_errors}"
msgstr ""

